---
sudo: required

language: python

before_install:
  - openssl aes-256-cbc -K $encrypted_756f7484f8dc_key -iv $encrypted_756f7484f8dc_iv -in molecule/default/clouds.yml.enc -out molecule/default/clouds.yml -d

install:
  - pip install -r test-requirements.txt

env:
  - TOX_ENV=ansible23
  - TOX_ENV=ansible24

script:
  - tox -e $TOX_ENV

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    use_notice: true
