---
sudo: required
language: python
#services:
#  - docker
#before_install:
#  - docker pull solita/ubuntu-systemd:16.04
#  - |
#    docker run -d --privileged --name osism-systemd --hostname osism-systemd \
#    --security-opt seccomp=unconfined --tmpfs /run --tmpfs /run/lock \
#    -v /sys/fs/cgroup:/sys/fs/cgroup:ro -t solita/ubuntu-systemd:16.04
install:
  - pip install -r test-requirements.txt
script:
  - tox
notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    use_notice: true
