---
- name: Ensure docker-compose is not installed
  apt:
    name: docker-compose
    state: absent
  become: true

- name: Block installation of docker-compose package
  copy:
    content: |
      Package: docker-compose
      Pin: version *
      Pin-Priority: -1
    dest: /etc/apt/preferences.d/docker-compose
  become: true

- name: Download docker-compose binary
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0755
  become: true
  when: docker_compose_install_from_url|bool

- name: Copy docker-compose binary
  copy:
    src: binaries/docker-compose
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0755
  become: true
  when: not docker_compose_install_from_url|bool

- name: Get checksum of docker-compose binary
  stat:
    path: /usr/local/bin/docker-compose
    checksum_algorithm: sha256
  register: p

- name: Check checksum of docker-compose binary
  fail:
    msg: "Expected checksum of docker-compose does not match"
  when:
    - "p.stat.checksum != docker_compose_checksum"
